configuration:
  width: 450 
  height: 450
  luminosity-label: '%1$.1f fb^{-1} at #sqrt{s} = 13 TeV'
  experiment: " CMS"
  #extra-label: "Preliminary"
  extra-label: "Work in Progress"
  root: ''
  luminosity: 137144 
  luminosity-error: 0.00
  #luminosity-error: 0.025
  error-fill-style: 3154
  error-fill-color: "#ee556270"
  ratio-fit-error-fill-style: 1001
  ratio-fit-error-fill-color: "#aa556270"
  ratio-fit-line-color: "#0B486B"
  blinded-range-fill-color: "#29556270"
  blinded-range-fill-style: 1001
  yields-table-align: v
  book-keeping-file: 'plots.root'
  yields-table-numerical-precision-yields: 2

files: 
  include: ['files.yml']

systematics:
#  - ttbb_xsec:     {type: const, value: 1.055, on: 'hist_ttbb.root'}
#  - ttbj_xsec:     {type: const, value: 1.055, on: 'hist_ttbj.root'}
#  - ttcc_xsec:     {type: const, value: 1.055, on: 'hist_ttcc.root'}
#  - ttlf_xsec:     {type: const, value: 1.055, on: 'hist_ttLF.root'}
#  - ttother_xsec:  {type: const, value: 1.055, on: 'hist_ttother.root'}
#  - ttbkg_xsec:    {type: const, value: 1.055, on: 'hist_ttbkg.root'}
#  - ttbb_xsec2:    {type: const, value: 1.3, on: 'hist_ttbb.root'}
#  - ttcc_xsec2:    {type: const, value: 1.5, on: 'hist_ttcc.root'}
#  - other_xsec1:   {type: const, value: 1.1, on: 'hist_zjets.root'}
#  - other_xsec2:   {type: const, value: 1.1, on: 'hist_zjets10to50.root'}
#  - other_xsec3:   {type: const, value: 1.1, on: 'hist_wjets.root'}
#  - other_xsec4:   {type: const, value: 1.1, on: 'hist_ww.root'}
#  - other_xsec5:   {type: const, value: 1.1, on: 'hist_wz.root'}
#  - other_xsec6:   {type: const, value: 1.1, on: 'hist_zz.root'}
#  - other_xsec7:   {type: const, value: 1.1, on: 'hist_tchannel.root'}
#  - other_xsec8:   {type: const, value: 1.1, on: 'hist_tbarchannel.root'}
#  - other_xsec9:   {type: const, value: 1.1, on: 'hist_tWchannel.root'}
#  - other_xsec10:  {type: const, value: 1.1, on: 'hist_tbarWchannel.root'}
#  - other_xsec11:  {type: const, value: 1.1, on: 'hist_ttH.root'}
#  - other_xsec12:  {type: const, value: 1.1, on: 'hist_ttW.root'}
#  - other_xsec13:  {type: const, value: 1.1, on: 'hist_ttZ.root'}
#  - pu
#  - musf
#  - musf
#  - jec
#  - jer
#  - scale: {type: shape, on: 'hist_ttbb.root'}
#  - scale: {type: shape, on: 'hist_ttbj.root'}
#  - scale: {type: shape, on: 'hist_ttcc.root'}
#  - scale: {type: shape, on: 'hist_ttLF.root'}
#  - scale: {type: shape, on: 'hist_ttother.root'}
#  - scale: {type: shape, on: 'hist_ttbkg.root'}
#  - scale: {type: shape, on: 'hist_ttH.root'}
#  - scale: {type: shape, on: 'hist_ttW.root'}
#  - scale: {type: shape, on: 'hist_ttZ.root'}
#  - ps: {type: shape, on: 'hist_ttbb.root'}
#  - ps: {type: shape, on: 'hist_ttbj.root'}
#  - ps: {type: shape, on: 'hist_ttcc.root'}
#  - ps: {type: shape, on: 'hist_ttLF.root'}
#  - ps: {type: shape, on: 'hist_ttother.root'}
#  - ps: {type: shape, on: 'hist_ttbkg.root'}
#  - hdamp: {type: shape, on: 'hist_ttbb.root'}
#  - hdamp: {type: shape, on: 'hist_ttbj.root'}
#  - hdamp: {type: shape, on: 'hist_ttcc.root'}
#  - hdamp: {type: shape, on: 'hist_ttLF.root'}
#  - hdamp: {type: shape, on: 'hist_ttother.root'}
#  - pdf: {type: shape, on: 'hist_ttbb.root'}
#  - pdf: {type: shape, on: 'hist_ttbj.root'}
#  - pdf: {type: shape, on: 'hist_ttcc.root'}
#  - pdf: {type: shape, on: 'hist_ttlf.root'}
#  - pdf: {type: shape, on: 'hist_ttother.root'}
#  - TuneCP5: {type: shape, on: 'hist_ttbb.root'}
#  - TuneCP5: {type: shape, on: 'hist_ttbj.root'}
#  - TuneCP5: {type: shape, on: 'hist_ttcc.root'}
#  - TuneCP5: {type: shape, on: 'hist_ttLF.root'}
#  - TuneCP5: {type: shape, on: 'hist_ttother.root'}
#  - lf
#  - hf
#  - lfstat1
#  - lfstat2
#  - hfstat1
#  - hfstat2
#  - cferr1
#  - cferr2

plots:
  include: ['histos_ttlj.yml']

legend:
#  position: [0.18, 0.68, 0.92, 0.89]
  position: [0.18, 0.73, 0.92, 0.89] #For DNN
  columns: 5

groups:
  include: ['groups.yml']

#  - gamma: {type: ln, prior: 1.072, pretty-name: "Gamma"}  # Log-normal systematics, +7.2%, -2.97%, exp(+/- 1 * log(prior))
