configuration:
  width: 450 
  height: 450
  luminosity-label: '%1$.1f fb^{-1} at #sqrt{s} = 13 TeV'
  experiment: " CMS"
  #extra-label: "Preliminary"
  extra-label: "Work in Progress"
  root: ''
  luminosity: 35922 
  luminosity-error: 0.025
  error-fill-style: 3154
  error-fill-color: "#ee556270"
  ratio-fit-error-fill-style: 1001
  ratio-fit-error-fill-color: "#aa556270"
  ratio-fit-line-color: "#0B486B"
  blinded-range-fill-color: "#29556270"
  blinded-range-fill-style: 1001
  yields-table-align: v
  book-keeping-file: 'plots.root'
  yields-table-numerical-precision-yields: 2

files: 
  include: ['files/files16.yml'] # For basic plots
#  include: ['files/files16_qcd.yml'] # For QCD region plots
#  include: ['files/files16_test.yml'] # Drawing without systematics 

systematics:
#  - ttbb_xsec:     {type: const, value: 1.055, on: 'hist_ttbb.root'}
#  - ttbj_xsec:     {type: const, value: 1.055, on: 'hist_TTLJ_PowhegPythia_ttbj.root'}
#  - ttcc_xsec:     {type: const, value: 1.055, on: 'hist_TTLJ_PowhegPythia_ttcc.root'}
#  - ttlf_xsec:     {type: const, value: 1.055, on: 'hist_TTLJ_PowhegPythia_ttLF.root'}
#  - ttother_xsec:  {type: const, value: 1.055, on: 'hist_TTLJ_PowhegPythia_ttother.root'}
#  - ttbkg_xsec:    {type: const, value: 1.055, on: 'hist_TT_PowhegPythiaBkg.root'}
#  - ttbb_xsec2:    {type: const, value: 1.3, on: 'hist_ttbb.root'}
#  - ttcc_xsec2:    {type: const, value: 1.5, on: 'hist_TTLJ_PowhegPythia_ttcc.root'}
#  - other_xsec1:   {type: const, value: 1.1, on: 'hist_ZJets_M10to50_aMCatNLO.root'}
#  - other_xsec2:   {type: const, value: 1.1, on: 'hist_ZJets_M50_aMCatNLO.root'}
#  - other_xsec3:   {type: const, value: 1.1, on: 'hist_WJets_aMCatNLO.root'}
#  - other_xsec4:   {type: const, value: 1.1, on: 'hist_WW_Pythia.root'}
#  - other_xsec5:   {type: const, value: 1.1, on: 'hist_WZ_Pythia.root'}
#  - other_xsec6:   {type: const, value: 1.1, on: 'hist_ZZ_Pythia.root'}
#  - other_xsec7:   {type: const, value: 1.1, on: 'hist_SingleTop_t_Powheg.root'}
#  - other_xsec8:   {type: const, value: 1.1, on: 'hist_SingleTop_tW_Powheg.root'}
#  - other_xsec9:   {type: const, value: 1.1, on: 'hist_SingleTbar_t_Powheg.root'}
#  - other_xsec10:  {type: const, value: 1.1, on: 'hist_SingleTbar_tW_Powheg.root'}
#  - other_xsec11:  {type: const, value: 1.1, on: 'hist_ttHbb_PowhegPythia.root'}
#  - other_xsec12:  {type: const, value: 1.1, on: 'hist_ttW_Madgraph.root'}
#  - other_xsec13:  {type: const, value: 1.1, on: 'hist_ttZ_Madgraph.root'}
  - pu
  - musf
  - mutrg
  - elsf
  - eltrg
  - jec
  - jer
  - lf
  - hf
  - lfstat1
  - lfstat2
  - hfstat1
  - hfstat2
  - cferr1
  - cferr2
  - sw: {type: shape, on: 'hist_TTLJ_PowhegPythia_ttbb.root'}
  - sw: {type: shape, on: 'hist_TTLJ_PowhegPythia_ttbj.root'}
  - sw: {type: shape, on: 'hist_TTLJ_PowhegPythia_ttcc.root'}
  - sw: {type: shape, on: 'hist_TTLJ_PowhegPythia_ttLF.root'}
  - sw: {type: shape, on: 'hist_TTLJ_PowhegPythia_ttother.root'}
  - sw: {type: shape, on: 'hist_TT_PowhegPythiaBkg.root'}
  - ps: {type: shape, on: 'hist_TTLJ_PowhegPythia_ttbb.root'}
  - ps: {type: shape, on: 'hist_TTLJ_PowhegPythia_ttbj.root'}
  - ps: {type: shape, on: 'hist_TTLJ_PowhegPythia_ttcc.root'}
  - ps: {type: shape, on: 'hist_TTLJ_PowhegPythia_ttLF.root'}
  - ps: {type: shape, on: 'hist_TTLJ_PowhegPythia_ttother.root'}
  - ps: {type: shape, on: 'hist_TT_PowhegPythiaBkg.root'}
  - hdamp: {type: shape, on: 'hist_TTLJ_PowhegPythia_ttbb.root'}
  - hdamp: {type: shape, on: 'hist_TTLJ_PowhegPythia_ttbj.root'}
  - hdamp: {type: shape, on: 'hist_TTLJ_PowhegPythia_ttcc.root'}
  - hdamp: {type: shape, on: 'hist_TTLJ_PowhegPythia_ttLF.root'}
  - hdamp: {type: shape, on: 'hist_TTLJ_PowhegPythia_ttother.root'}
  - pdf: {type: shape, on: 'hist_TTLJ_PowhegPythia_ttbb.root'}
  - pdf: {type: shape, on: 'hist_TTLJ_PowhegPythia_ttbj.root'}
  - pdf: {type: shape, on: 'hist_TTLJ_PowhegPythia_ttcc.root'}
  - pdf: {type: shape, on: 'hist_TTLJ_PowhegPythia_ttlf.root'}
  - pdf: {type: shape, on: 'hist_TTLJ_PowhegPythia_ttother.root'}
  - pdf: {type: shape, on: 'hist_TT_PowhegPythiaBkg.root'}
  - tune: {type: shape, on: 'hist_TTLJ_PowhegPythia_ttbb.root'}
  - tune: {type: shape, on: 'hist_TTLJ_PowhegPythia_ttbj.root'}
  - tune: {type: shape, on: 'hist_TTLJ_PowhegPythia_ttcc.root'}
  - tune: {type: shape, on: 'hist_TTLJ_PowhegPythia_ttLF.root'}
  - tune: {type: shape, on: 'hist_TTLJ_PowhegPythia_ttother.root'}
  - tune: {type: shape, on: 'hist_TT_PowhegPythiaBkg.root'}

plots:
  include: ['histos/histos_ttlj.yml'] # Basic plot list
  # include: ['histos/histos_qcd.yml'] # QCD region plot list
  # include: ['histos/histos_yields.yml'] # nJet hist only

legend:
  position: [0.18, 0.68, 0.92, 0.89]
  columns: 5

groups:
  include: ['groups.yml']

#  - gamma: {type: ln, prior: 1.072, pretty-name: "Gamma"}  # Log-normal systematics, +7.2%, -2.97%, exp(+/- 1 * log(prior))
