#generated-events : sum_of_weights (EventInfo->GetBinContent(2))

#'hist_DataSingleMuB.root':
#  type: data
#  legend: 'Data'
#  pretty-name: 'Data'
#  marker-size: 0.6
#  group: GData
#
#'hist_DataSingleMuC.root':
#  type: data
#  legend: 'Data'
#  pretty-name: 'Data'
#  marker-size: 0.6
#  group: GData
#
#'hist_DataSingleMuD.root':
#  type: data
#  legend: 'Data'
#  pretty-name: 'Data'
#  marker-size: 0.6
#  group: GData
#
#'hist_DataSingleMuE.root':
#  type: data
#  legend: 'Data'
#  pretty-name: 'Data'
#  marker-size: 0.6
#  group: GData
#
#'hist_DataSingleMuF.root':
#  type: data
#  legend: 'Data'
#  pretty-name: 'Data'
#  marker-size: 0.6
#  group: GData
#
'hist_DataSingleEGB.root':
  type: data
  legend: 'Data'
  pretty-name: 'Data'
  marker-size: 0.6
  group: GData

'hist_DataSingleEGC.root':
  type: data
  legend: 'Data'
  pretty-name: 'Data'
  marker-size: 0.6
  group: GData

'hist_DataSingleEGD.root':
  type: data
  legend: 'Data'
  pretty-name: 'Data'
  marker-size: 0.6
  group: GData

'hist_DataSingleEGE.root':
  type: data
  legend: 'Data'
  pretty-name: 'Data'
  marker-size: 0.6
  group: GData

'hist_DataSingleEGF.root':
  type: data
  legend: 'Data'
  pretty-name: 'Data'
  marker-size: 0.6
  group: GData

'hist_TTLJ_PowhegPythia_ttbb.root':
  type: mc
  pretty-name: 'TTLJ_PowhegPythia_ttbb'
  cross-section: 365.34
  generated-events: 109194238 
  fill-color: "#330000"
  legend: "ttbb"
  yields-group: '0\ttbar\bbbar'
  order: 0

'hist_TTLJ_PowhegPythia_ttbj.root':
  type: mc
  pretty-name: 'TTLJ_PowhegPythia_ttbj'
  cross-section: 365.34
  generated-events: 109194238 
  fill-color: '#660000'
  legend: 'ttbj'
  yields-group: '1\ttbar bj'
  order: 1

'hist_TTLJ_PowhegPythia_ttcc.root':
  type: mc
  pretty-name: 'TTLJ_PowhegPythia_ttcc'
  cross-section: 365.34
  generated-events: 109194238 
  fill-color: '#990000'
  legend: 'ttcc'
  yields-group: '2\ttbar\ccbar'
  order: 2

'hist_TTLJ_PowhegPythia_ttLF.root':
  type: mc
  pretty-name: 'TTLJ_PowhegPythia_ttLF'
  cross-section: 365.34
  generated-events: 109194238 
  fill-color: '#cc0000'
  legend: 'ttLF'
  yields-group: '3\ttbar LF'
  order: 3

'hist_TTLJ_PowhegPythia_ttother.root':
  type: mc
  pretty-name: 'TTLJ_PowhegPythia_ttother'
  cross-section: 365.34
  generated-events: 109194238 
  fill-color: '#ff6666'
  legend: 'ttBkg'
  group: GttBkg
  yields-group: '4\ttbar Bkg'
  order: 4

'hist_TTLL_PowhegPythiaBkg.root':
  type: mc
  pretty-name: 'TTLL_PowhegPythiaBkg'
  cross-section: 88.29 
  generated-events: 68595608 
  fill-color: '#ff6666'
  legend: 'ttBkg'
  group: GttBkg
  yields-group: '4\ttbar Bkg'
  order: 5

'hist_TTLJ_PowhegPythiaBkg.root':
  type: mc
  pretty-name: 'TTLJ_PowhegPythiaBkg'
  cross-section: 365.34 
  generated-events: 109194238 
  fill-color: '#ff6666'
  legend: 'ttBkg'
  group: GttBkg
  yields-group: '4\ttbar Bkg'
  order: 6

'hist_TTJJ_PowhegPythiaBkg.root':
  type: mc
  pretty-name: 'TTJJ_PowhegPythiaBkg'
  cross-section: 377.96 
  generated-events: 129211204 
  fill-color: '#ff6666'
  legend: 'ttBkg'
  group: GttBkg
  yields-group: '4\ttbar Bkg'
  order: 7

'hist_ttHTobb_PowhegPythia.root':
  type: mc
  pretty-name: 'ttHTobb_PowhegPythia'
  cross-section: 0.2934
  generated-events: 7833734
  fill-color: '#ff66ff'
  legend: 'ttX'
  group: GttX
  order: 8 

'hist_ttHToNonbb_PowhegPythia.root':
  type: mc
  pretty-name: 'ttHToNonbb_PowhegPythia'
  cross-section: 0.2151
  generated-events: 7814711
  fill-color: '#ff66ff'
  legend: 'ttX'
  group: GttX
  order: 9

'hist_ttWToLNu_aMCatNLOMadspinPythia.root':
  type: mc
  pretty-name: 'ttWToLNu_aMCatNLOMadspinPythia'
  cross-section: 0.2043
  generated-events: 2686141
  fill-color: '#ff66ff'
  legend: 'ttX'
  group: GttX
  order: 10

'hist_ttWToQQ_aMCatNLOMadspinPythia.root':
  type: mc
  pretty-name: 'ttWToQQ_aMCatNLOMadspinPythia'
  cross-section: 0.4062
  generated-events: 441560
  fill-color: '#ff66ff'
  legend: 'ttX'
  group: GttX
  order: 11

'hist_ttZToLLNuNu_aMCatNLOMadspinPythia.root':
  type: mc
  pretty-name: 'ttZToLLNuNu_aMCatNLOMadspinPythia'
  cross-section: 0.2529
  generated-events: 3570720
  fill-color: '#ff66ff'
  legend: 'ttX'
  group: GttX
  order: 12

'hist_ttZToQQ_aMCatNLOMadspinPythia.root':
  type: mc
  pretty-name: 'ttZToQQ_aMCatNLOMadspinPythia'
  cross-section: 0.5297
  generated-events: 356286
  fill-color: '#ff66ff'
  legend: 'ttX'
  group: GttX
  order: 13

'hist_SingleTop_s_aMCatNLOPythia.root':
  type: mc
  pretty-name: 'SingleTop_s_aMCatNLOPythia'
  cross-section: 3.36 
  generated-events: 6185062
  fill-color: '#990099'
  legend: 'SingleT'
  group: GSingleT
#yields-group: '5Other'
  order: 14

'hist_SingleTop_t_PowhegPythia.root':
  type: mc
  pretty-name: 'SingleTop_t_PowhegPythia'
  cross-section: 136.02 
  generated-events: 5982064 
  fill-color: '#990099'
  legend: 'SingleT'
  group: GSingleT
# yields-group: '5Other'
  order: 15

'hist_SingleTop_tW_PowhegPythia.root':
  type: mc
  pretty-name: 'SingleTop_tW_PowhegPythia'
  cross-section: 35.85
  generated-events: 7884388 
  fill-color: '#990099'
  legend: 'SingleT'
  group: GSingleT
# yields-group: '5Other'
  order: 16

'hist_SingleTbar_t_PowhegPythia.root':
  type: mc
  pretty-name: 'SingleTbar_t_PowhegPythia'
  cross-section: 80.95
  generated-events: 3675910 
  fill-color: '#990099'
  legend: 'SingleT'
  group: GSingleT
# yields-group: '5Other'
  order: 17

'hist_SingleTbar_tW_PowhegPythia.root':
  type: mc
  pretty-name: 'SingleTbar_tW_PowhegPythia'
  cross-section: 35.85
  generated-events: 7686032 
  fill-color: '#990099'
  legend: 'SingleT'
  group: GSingleT
# yields-group: '5Other'
  order: 18

'hist_WW_Pythia.root':
  type: mc
  pretty-name: 'WW_Pythia'
  cross-section: 118.7
  generated-events: 7791498
  fill-color: '#00cccc'
  legend: 'VV'
  group: GVV
# yields-group: '5Other'
  order: 19

'hist_WZ_Pythia.root':
  type: mc
  pretty-name: 'WZ_Pythia'
  cross-section: 47.13
  generated-events: 3928630
  fill-color: '#00cccc'
  legend: 'VV'
  group: GVV
# yields-group: '5Other'
  order: 20

'hist_ZZ_Pythia.root':
  type: mc
  pretty-name: 'ZZ_Pythia'
  cross-section: 16.523
  generated-events: 1949768
  fill-color: '#00cccc'
  legend: 'VV'
  group: GVV
# yields-group: '5Other'
  order: 21

'hist_ZJets_M50_aMCatNLOPythia.root':
  type: mc
  pretty-name: 'ZJets_M50_aMCatNLOPythia'
  cross-section: 6225.42 
  generated-events: 123485957 
  fill-color: '#000099'
  legend: 'ZJets'
  group: GZJets
# yields-group: '5Other'
  order: 22

'hist_ZJets_M10to50_MadgraphPythia.root':
  type: mc
  pretty-name: 'ZJets_M10to50_MadgraphPythia'
  cross-section: 18610.0
  generated-events: 39489654 
  fill-color: '#000099'
  legend: 'ZJets'
  group: GZJets
# yields-group: '5Other'
  order: 23

#'hist_WJetsToLNu_MadgraphPythia.root':
#  type: mc
#  pretty-name: 'WJetsToLNu_MadgraphPythia'
#  cross-section: 61526 #pre: 61526.7
#  generated-events: 77631180 
#  fill-color: '#ff9933'
#  legend: 'WJets'
#  group: GWJets
## yields-group: '5Other'
#  order: 23
#
'hist_W1JetsToLNu_MadgraphPythia.root':
  type: mc
  pretty-name: 'W1JetsToLNu_MadgraphPythia'
  cross-section: 9625 
  generated-events: 54106926
  fill-color: '#ff9933'
  legend: 'WJets'
  group: GWJets
  order: 24

'hist_W2JetsToLNu_MadgraphPythia.root':
  type: mc
  pretty-name: 'W2JetsToLNu_MadgraphPythia'
  cross-section: 2793
  generated-events: 6570442
  fill-color: '#ff9933'
  legend: 'WJets'
  group: GWJets
  order: 25

'hist_W3JetsToLNu_MadgraphPythia.root':
  type: mc
  pretty-name: 'W3JetsToLNu_MadgraphPythia'
  cross-section: 992.5
  generated-events: 19669693
  fill-color: '#ff9933'
  legend: 'WJets'
  group: GWJets
  order: 26

'hist_W4JetsToLNu_MadgraphPythia.root':
  type: mc
  pretty-name: 'W4JetsToLNu_MadgraphPythia'
  cross-section: 544.3
  generated-events: 11074019
  fill-color: '#ff9933'
  legend: 'WJets'
  group: GWJets
  order: 27

