#generated-events : sum_of_weights (EventInfo->GetBinContent(2))

#'hist_DataSingleMuB.root':
#  type: data
#  legend: 'Data'
#  pretty-name: 'Data'
#  marker-size: 0.6
#  group: GData
#
#'hist_DataSingleMuC.root':
#  type: data
#  legend: 'Data'
#  pretty-name: 'Data'
#  marker-size: 0.6
#  group: GData
#
#'hist_DataSingleMuD.root':
#  type: data
#  legend: 'Data'
#  pretty-name: 'Data'
#  marker-size: 0.6
#  group: GData
#
#'hist_DataSingleMuE.root':
#  type: data
#  legend: 'Data'
#  pretty-name: 'Data'
#  marker-size: 0.6
#  group: GData
#
#'hist_DataSingleMuF.root':
#  type: data
#  legend: 'Data'
#  pretty-name: 'Data'
#  marker-size: 0.6
#  group: GData

'hist_DataSingleEGB.root':
  type: data
  legend: 'Data'
  pretty-name: 'Data'
  marker-size: 0.6
  group: GData

'hist_DataSingleEGC.root':
  type: data
  legend: 'Data'
  pretty-name: 'Data'
  marker-size: 0.6
  group: GData

'hist_DataSingleEGD.root':
  type: data
  legend: 'Data'
  pretty-name: 'Data'
  marker-size: 0.6
  group: GData

'hist_DataSingleEGE.root':
  type: data
  legend: 'Data'
  pretty-name: 'Data'
  marker-size: 0.6
  group: GData

'hist_DataSingleEGF.root':
  type: data
  legend: 'Data'
  pretty-name: 'Data'
  marker-size: 0.6
  group: GData

'hist_TTLJ_PowhegPythia_ttbb.root':
  type: mc
  pretty-name: 'TTLJ_PowhegPythia_ttbb'
  cross-section: 365.34
#  generated-events: 104564754 
  generated-events: 109194238 #109194238
  fill-color: "#330000"
  legend: "ttbb"
  yields-group: '0\ttbar\bbbar'
  order: 0
#  scale: 0.992

'hist_TTLJ_PowhegPythia_ttbj.root':
  type: mc
  pretty-name: 'TTLJ_PowhegPythia_ttbj'
  cross-section: 365.34
  generated-events: 104111550 #109194238
  fill-color: '#660000'
  legend: 'ttbj'
  yields-group: '1\ttbar bj'
  order: 1
#  scale: 0.997

'hist_PowhegPythia_ttcc.root':
  type: mc
  pretty-name: 'TTLJ_PowhegPythia_ttcc'
  cross-section: 365.34
  generated-events: 106421862 #109194238
  fill-color: '#990000'
  legend: 'ttcc'
  yields-group: '2\ttbar\ccbar'
  order: 2
#  scale: 0.871

'hist_PowhegPythia_ttLF.root':
  type: mc
  pretty-name: 'TTLJ_PowhegPythia_ttLF'
  cross-section: 365.34
  generated-events: 109194238 #109194238
  fill-color: '#cc0000'
  legend: 'ttLF'
  yields-group: '3\ttbar LF'
  order: 3
  scale: 0.890

'hist_PowhegPythia_ttother.root':
  type: mc
  pretty-name: 'TTLJ_PowhegPythia_ttother'
  cross-section: 365.34
  generated-events: 109194238 #109194238
  fill-color: '#ff6666'
  legend: 'ttBkg'
  group: GttBkg
  yields-group: '4\ttbar Bkg'
  order: 4

'hist_TTJJ_PowhegPythiaBkg.root':
  type: mc
  pretty-name: 'TTJJ_PowhegPythiaBkg'
  cross-section: 377.96 
  generated-events: 129211204 #? 
  fill-color: '#ff6666'
  legend: 'ttBkg'
  group: GttBkg
  yields-group: '4\ttbar Bkg'
  order: 5

#'hist_ttH.root':
#  type: mc
#  pretty-name: 'ttHbb_PowhegPythia'
#  cross-section: 0.2923
#  generated-events: 3772592
#  fill-color: '#ff66ff'
#  legend: 'ttV'
#  group: GttV
#yields-group: '5Other'
#  order: 7

'hist_ttWToLNu_aMCatNLOMadspinPythia.root':
  type: mc
  pretty-name: 'ttWToLNu_aMCatNLOMadspinPythia'
  cross-section: 0.2043 
  generated-events: 2686141 #?
  fill-color: '#ff66ff'
  legend: 'ttV'
  group: GttV
  yields-group: '5Other'
  order: 9

'hist_ttWToQQ_aMCatNLOMadspinPythia.root':
  type: mc
  pretty-name: 'ttWToQQ_aMCatNLOMadspinPythia'
  cross-section: 0.4062
  generated-events: 441560 #?
  fill-color: '#ff66ff'
  legend: 'ttV'
  group: GttV
  yields-group: '5Other'
  order: 10

#'hist_ttZ.root':
#  type: mc
#  pretty-name: 'ttZ_Madgraph'
#  cross-section: 0.2529
#  generated-events: 3685785
#  fill-color: '#ff66ff'
#  legend: 'ttV'
#  group: GttV
# yields-group: '5Other'
#  order: 11

'hist_SingleTop_s_aMCatNLOPythia.root':
  type: mc
  pretty-name: 'SingleTops'
  cross-section: 3.36
  generated-events: 6185062
  fill-color: '#990099'
  legend: 'SingleT'
  group: GSingleT
  yields-group: '5Other'
  order: 12

'hist_tchannel.root':
  type: mc
  pretty-name: 't_Powheg'
  cross-section: 136.02
  generated-events: 5982064
  fill-color: '#990099'
  legend: 'SingleT'
  group: GSingleT
  yields-group: '5Other'
  order: 13

#'hist_tbarchannel.root':
#  type: mc
#  pretty-name: 'tbar_Powheg'
#  cross-section: 80.95 
#  generated-events: 38811017 
#  fill-color: '#990099'
#  legend: 'SingleT'
#  group: GSingleT
# yields-group: '5Other'
#  order: 14

'hist_tWchannel.root':
  type: mc
  pretty-name: 'tW_Powheg'
  cross-section: 35.85
  generated-events: 7884388 #same?
  fill-color: '#990099'
  legend: 'SingleT'
  group: GSingleT
  yields-group: '5Other'
  order: 15

#'hist_tbarWchannel.root':
#  type: mc
#  pretty-name: 'tbarW_Powheg'
#  cross-section: 35.85
#  generated-events: 6933094 
#  fill-color: '#990099'
#  legend: 'SingleT'
#  group: GSingleT
# yields-group: '5Other'
#  order: 16

'hist_ww.root':
  type: mc
  pretty-name: 'WW_Pythia'
  cross-section: 118.7
  generated-events: 7791498 #same?
  fill-color: '#00cccc'
  legend: 'VV'
  group: GVV
  yields-group: '5Other'
  order: 17

'hist_wz.root':
  type: mc
  pretty-name: 'WZ_Pythia'
  cross-section: 47.13
  generated-events: 3928630 #same?
  fill-color: '#00cccc'
  legend: 'VV'
  group: GVV
  yields-group: '5Other'
  order: 18

'hist_zz.root':
  type: mc
  pretty-name: 'ZZ_Pythia'
  cross-section: 16.523
  generated-events: 1949768 #same?
  fill-color: '#00cccc'
  legend: 'VV'
  group: GVV
  yields-group: '5Other'
  order: 19

'hist_zjets.root':
  type: mc
  pretty-name: 'ZJets_M50_aMCatNLO'
  cross-section: 5765.4
  generated-events: 123485957 #same?
  fill-color: '#000099'
  legend: 'ZJets'
  group: GZJets
  yields-group: '5Other'
  order: 20

'hist_zjets10to50.root':
  type: mc
  pretty-name: 'ZJets_M10to50_aMCatNLO'
  cross-section: 18610.0
  generated-events: 39489654 #same?
  fill-color: '#000099'
  legend: 'ZJets'
  group: GZJets
  yields-group: '5Other'
  order: 21

#'hist_wjets.root':
#  type: mc
#  pretty-name: 'WJets_aMCatNLO'
#  cross-section: 61526.7
#  generated-events: 44587448 #same?
#  fill-color: '#ff9933'
#  legend: 'WJets'
#  group: GWJets
#  yields-group: '5Other'
#  order: 22

'hist_W1JetsToLNu_MadgraphPythia.root':
  type: mc
  pretty-name: 'W1JetsToLNu'
  cross-section: 9625
  generated-events: 54106926
  fill-color: '#ff9933'
  legend: 'WJets'
  group: GWJets
  yields-group: '5Other'
  order: 23

'hist_W2JetsToLNu_MadgraphPythia.root':
  type: mc
  pretty-name: 'WJets_aMCatNLO'
  cross-section: 2793
  generated-events: 6570442
  fill-color: '#ff9933'
  legend: 'WJets'
  group: GWJets
  yields-group: '5Other'
  order: 24

'hist_W3JetsToLNu_MadgraphPythia.root':
  type: mc
  pretty-name: 'WJets_aMCatNLO'
  cross-section: 992.5
  generated-events: 19669693
  fill-color: '#ff9933'
  legend: 'WJets'
  group: GWJets
  yields-group: '5Other'
  order: 25

'hist_W4JetsToLNu_MadgraphPythia.root':
  type: mc
  pretty-name: 'WJets_aMCatNLO'
  cross-section: 544.3
  generated-events: 11074019
  fill-color: '#ff9933'
  legend: 'WJets'
  group: GWJets
  yields-group: '5Other'
  order: 26
