GData:
  legend: 'Data'
  marker-size: 0.6
GWJets:
  fill-color: '#ff9933'
  legend: 'WJets'
GttBkg:
  fill-color: '#ff6666'
  legend: 'ttBkg'
GttX:
  fill-color: '#ff66ff'
  legend: 'ttX'
GZJets:
  fill-color: '#000099'
  legend: 'ZJets'
GSingleT:
  fill-color: '#990099'
  legend: 'SingleT'
GVV:
  fill-color: '#00cccc'
  legend: 'VV'
GQCD:
  fill-color: '#d0cfd4'
  legend: 'QCD'
