'h_keras_RecoAddbJetDeltaR_Ch1_S3':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf']
  log-y: true
  show-ratio: true

'h_keras_RecoAddbJetInvMass_Ch1_S3':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf']
  log-y: true
  show-ratio: true
