'h_LeptonPt_Ch0_S0':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf']
  log-y: true
  show-ratio: true

'h_LeptonEta_Ch0_S0':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf']
  log-y: true
  show-ratio: true

'h_nJets_Ch0_S0':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf']
  log-y: true
  show-ratio: true
  for-yields: true

'h_nbJets_Ch0_S0':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf']
  log-y: true
  show-ratio: true

'h_TransverseMass_Ch0_S0':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf']
  log-y: true
  show-ratio: true

'h_mindR_RecoAddbJetDeltaR_Ch0_S0':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf']
  log-y: true
  show-ratio: true

'h_mindR_RecoAddbJetInvMass_Ch0_S0':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf']
  log-y: true
  show-ratio: true

'h_mindR_RecoAddbJetDeltaEta_Ch0_S0':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf']
  log-y: true
  show-ratio: true

'h_mindR_RecoAddbJetDeltaPhi_Ch0_S0':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf']
  log-y: true
  show-ratio: true

'h_LeptonPt_Ch0_S1':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf']
  log-y: true
  show-ratio: true

'h_LeptonEta_Ch0_S1':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf']
  log-y: true
  show-ratio: true

'h_nJets_Ch0_S1':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf']
  log-y: true
  show-ratio: true
  for-yields: true

'h_nbJets_Ch0_S1':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf']
  log-y: true
  show-ratio: true

'h_TransverseMass_Ch0_S1':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf']
  log-y: true
  show-ratio: true

'h_mindR_RecoAddbJetDeltaR_Ch0_S1':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf']
  log-y: true
  show-ratio: true

'h_mindR_RecoAddbJetInvMass_Ch0_S1':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf']
  log-y: true
  show-ratio: true

'h_mindR_RecoAddbJetDeltaEta_Ch0_S1':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf']
  log-y: true
  show-ratio: true

'h_mindR_RecoAddbJetDeltaPhi_Ch0_S1':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf']
  log-y: true
  show-ratio: true

'h_LeptonPt_Ch0_S2':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf']
  log-y: true
  show-ratio: true

'h_LeptonEta_Ch0_S2':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf']
  log-y: true
  show-ratio: true

'h_nJets_Ch0_S2':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf']
  log-y: true
  show-ratio: true
  for-yields: true

'h_nbJets_Ch0_S2':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf']
  log-y: true
  show-ratio: true

'h_TransverseMass_Ch0_S2':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf']
  log-y: true
  show-ratio: true

'h_mindR_RecoAddbJetDeltaR_Ch0_S2':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf']
  log-y: true
  show-ratio: true

'h_mindR_RecoAddbJetInvMass_Ch0_S2':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf']
  log-y: true
  show-ratio: true

'h_mindR_RecoAddbJetDeltaEta_Ch0_S2':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf']
  log-y: true
  show-ratio: true

'h_mindR_RecoAddbJetDeltaPhi_Ch0_S2':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf']
  log-y: true
  show-ratio: true

'h_LeptonPt_Ch0_S3':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf']
  log-y: true
  show-ratio: true

'h_LeptonEta_Ch0_S3':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf']
  log-y: true
  show-ratio: true

'h_nJets_Ch0_S3':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf']
  log-y: true
  show-ratio: true
  for-yields: true

'h_nbJets_Ch0_S3':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf']
  log-y: true
  show-ratio: true

'h_TransverseMass_Ch0_S3':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf']
  log-y: true
  show-ratio: true

'h_mindR_RecoAddbJetDeltaR_Ch0_S3':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf']
  log-y: true
  show-ratio: true

'h_mindR_RecoAddbJetInvMass_Ch0_S3':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf']
  log-y: true
  show-ratio: true

'h_mindR_RecoAddbJetDeltaEta_Ch0_S3':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf']
  log-y: true
  show-ratio: true

'h_mindR_RecoAddbJetDeltaPhi_Ch0_S3':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf']
  log-y: true
  show-ratio: true

'h_LeptonPt_Ch1_S0':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf']
  log-y: true
  show-ratio: true

'h_LeptonEta_Ch1_S0':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf']
  log-y: true
  show-ratio: true

'h_nJets_Ch1_S0':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf']
  log-y: true
  show-ratio: true
  for-yields: true

'h_nbJets_Ch1_S0':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf']
  log-y: true
  show-ratio: true

'h_TransverseMass_Ch1_S0':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf']
  log-y: true
  show-ratio: true

'h_mindR_RecoAddbJetDeltaR_Ch1_S0':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf']
  log-y: true
  show-ratio: true

'h_mindR_RecoAddbJetInvMass_Ch1_S0':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf']
  log-y: true
  show-ratio: true

'h_mindR_RecoAddbJetDeltaEta_Ch1_S0':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf']
  log-y: true
  show-ratio: true

'h_mindR_RecoAddbJetDeltaPhi_Ch1_S0':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf']
  log-y: true
  show-ratio: true

'h_LeptonPt_Ch1_S1':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf']
  log-y: true
  show-ratio: true

'h_LeptonEta_Ch1_S1':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf']
  log-y: true
  show-ratio: true

'h_nJets_Ch1_S1':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf']
  log-y: true
  show-ratio: true
  for-yields: true

'h_nbJets_Ch1_S1':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf']
  log-y: true
  show-ratio: true

'h_TransverseMass_Ch1_S1':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf']
  log-y: true
  show-ratio: true

'h_mindR_RecoAddbJetDeltaR_Ch1_S1':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf']
  log-y: true
  show-ratio: true

'h_mindR_RecoAddbJetInvMass_Ch1_S1':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf']
  log-y: true
  show-ratio: true

'h_mindR_RecoAddbJetDeltaEta_Ch1_S1':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf']
  log-y: true
  show-ratio: true

'h_mindR_RecoAddbJetDeltaPhi_Ch1_S1':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf']
  log-y: true
  show-ratio: true

'h_LeptonPt_Ch1_S2':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf']
  log-y: true
  show-ratio: true

'h_LeptonEta_Ch1_S2':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf']
  log-y: true
  show-ratio: true

'h_nJets_Ch1_S2':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf']
  log-y: true
  show-ratio: true
  for-yields: true

'h_nbJets_Ch1_S2':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf']
  log-y: true
  show-ratio: true

'h_TransverseMass_Ch1_S2':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf']
  log-y: true
  show-ratio: true

'h_mindR_RecoAddbJetDeltaR_Ch1_S2':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf']
  log-y: true
  show-ratio: true

'h_mindR_RecoAddbJetInvMass_Ch1_S2':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf']
  log-y: true
  show-ratio: true

'h_mindR_RecoAddbJetDeltaEta_Ch1_S2':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf']
  log-y: true
  show-ratio: true

'h_mindR_RecoAddbJetDeltaPhi_Ch1_S2':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf']
  log-y: true
  show-ratio: true

'h_LeptonPt_Ch1_S3':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf']
  log-y: true
  show-ratio: true

'h_LeptonEta_Ch1_S3':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf']
  log-y: true
  show-ratio: true

'h_nJets_Ch1_S3':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf']
  log-y: true
  show-ratio: true
  for-yields: true

'h_nbJets_Ch1_S3':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf']
  log-y: true
  show-ratio: true

'h_TransverseMass_Ch1_S3':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf']
  log-y: true
  show-ratio: true

'h_mindR_RecoAddbJetDeltaR_Ch1_S3':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf']
  log-y: true
  show-ratio: true

'h_mindR_RecoAddbJetInvMass_Ch1_S3':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf']
  log-y: true
  show-ratio: true

'h_mindR_RecoAddbJetDeltaEta_Ch1_S3':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf']
  log-y: true
  show-ratio: true

'h_mindR_RecoAddbJetDeltaPhi_Ch1_S3':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf']
  log-y: true
  show-ratio: true

