'root16_qcd/hist_dataDriven_DataSingleMu.root':
  type: data
  legend: 'Data'
  pretty-name: 'DataMu'
  marker-size: 0.6
  group: GData

'root16_qcd/hist_dataDriven_DataSingleEG.root':
  type: data
  legend: 'Data'
  pretty-name: 'DataEG'
  marker-size: 0.6
  group: GData

'root16_qcd/hist_dataDriven_ttZ_Madgraph.root':
  type: mc
  pretty-name: 'ttZ_Madgraph'
  cross-section: 0.2529
  generated-events: 3685785.0
  fill-color: '#ff66ff'
  group: GttX
  order: 8
  #scale: 0.915188

'root16_qcd/hist_dataDriven_ttW_Madgraph.root':
  type: mc
  pretty-name: 'ttW_Madgraph'
  cross-section: 0.2043
  generated-events: 2676676.0
  fill-color: '#ff66ff'
  group: GttX
  order: 7
  #scale: 0.915188

'root16_qcd/hist_dataDriven_ttHbb_PowhegPythia.root':
  type: mc
  pretty-name: 'ttHbb_PowhegPythia'
  cross-section: 0.2923
  generated-events: 3772592.0
  fill-color: '#ff66ff'
  group: GttX
  order: 6
  #scale: 0.915188

'root16_qcd/hist_dataDriven_SingleTbar_t_Powheg.root':
  type: mc
  pretty-name: 'SingleTbar_t_Powheg'
  cross-section: 80.95
  generated-events: 38811017.0
  fill-color: '#990099'
  group: GSingleT
  order: 10
  #scale: 0.960297

'root16_qcd/hist_dataDriven_SingleTbar_tW_Powheg.root':
  type: mc
  pretty-name: 'SingleTbar_tW_Powheg'
  cross-section: 35.85
  generated-events: 6933094.0
  fill-color: '#990099'
  group: GSingleT
  order: 12
  #scale: 0.960297

'root16_qcd/hist_dataDriven_SingleTop_t_Powheg.root':
  type: mc
  pretty-name: 'SingleTop_t_Powheg'
  cross-section: 136.02
  generated-events: 67240808.0
  fill-color: '#990099'
  group: GSingleT
  order: 9
  #scale: 0.960297

'root16_qcd/hist_dataDriven_SingleTop_tW_Powheg.root':
  type: mc
  pretty-name: 'SingleTop_tW_Powheg'
  cross-section: 35.85
  generated-events: 6952830.0
  fill-color: '#990099'
  group: GSingleT
  order: 11
  #scale: 0.960297

'root16_qcd/hist_dataDriven_ZZ_Pythia.root':
  type: mc
  pretty-name: 'ZZ_Pythia'
  cross-section: 16.523
  generated-events: 1988098.0
  fill-color: '#00cccc'
  group: GVV
  order: 15
  #scale: 0.936838

'root16_qcd/hist_dataDriven_ZJets_M50_aMCatNLO.root':
  type: mc
  pretty-name: 'ZJets_M50_aMCatNLO'
  cross-section: 6225.42
  generated-events: 81781064.0
  fill-color: '#000099'
  group: GZJets
  order: 16
  #scale: 0.936838

'root16_qcd/hist_dataDriven_ZJets_M10to50_aMCatNLO.root':
  type: mc
  pretty-name: 'ZJets_M10to50_aMCatNLO'
  cross-section: 18610.0
  generated-events: 99831562.0
  fill-color: '#000099'
  group: GZJets
  order: 17
  #scale: 0.936838

'root16_qcd/hist_dataDriven_WZ_Pythia.root':
  type: mc
  pretty-name: 'WZ_Pythia'
  cross-section: 47.13
  generated-events: 3995828.0
  fill-color: '#00cccc'
  group: GVV
  order: 14
  #scale: 0.936838

'root16_qcd/hist_dataDriven_WW_Pythia.root':
  type: mc
  pretty-name: 'WW_Pythia'
  cross-section: 118.7
  generated-events: 7981136.0
  fill-color: '#00cccc'
  group: GVV
  order: 13
  #scale: 0.936838

'root16_qcd/hist_dataDriven_WJets_aMCatNLO.root':
  type: mc
  pretty-name: 'WJets_aMCatNLO'
  cross-section: 61526.7
  generated-events: 177578225.0
  fill-color: '#ff9933'
  legend: 'WJets'
  order: 18
  #scale: 0.936838

'root16_qcd/hist_dataDriven_TT_PowhegPythiaBkg.root':
  type: mc
  pretty-name: 'TT_PowhegPythiaBkg'
  cross-section: 831.76
  generated-events: 76837652.0
  fill-color: '#ff6666'
  group: GttBkg
  order: 5
  #scale: 0.960297

'root16_qcd/hist_dataDriven_TTLJ_PowhegPythia_ttother.root':
  type: mc
  pretty-name: 'TTLJ_PowhegPythia_ttother'
  cross-section: 365.34
  generated-events: 152627564.0
  fill-color: '#ff6666'
  group: GttBkg
  order: 4
  #scale: 0.936838

'root16_qcd/hist_dataDriven_TTLJ_PowhegPythia_ttcc.root':
  type: mc
  pretty-name: 'TTLJ_PowhegPythia_ttcc'
  cross-section: 365.34
  generated-events: 152627564.0
  fill-color: '#990000'
  legend: 'ttcc'
  order: 2
  #scale: 0.960297

'root16_qcd/hist_dataDriven_TTLJ_PowhegPythia_ttbj.root':
  type: mc
  pretty-name: 'TTLJ_PowhegPythia_ttbj'
  cross-section: 365.34
  generated-events: 152627564.0
  fill-color: '#660000'
  legend: 'ttbj'
  order: 1
  #scale: 0.772274

'root16_qcd/hist_dataDriven_TTLJ_PowhegPythia_ttbb.root':
  type: mc
  pretty-name: 'TTLJ_PowhegPythia_ttbb'
  cross-section: 365.34
  generated-events: 152627564.0
  fill-color: '#330000'
  legend: 'ttbb'
  order: 0
  #scale: 0.915188

'root16_qcd/hist_dataDriven_TTLJ_PowhegPythia_ttLF.root':
  type: mc
  pretty-name: 'TTLJ_PowhegPythia_ttLF'
  cross-section: 365.34
  generated-events: 152627564.0
  fill-color: '#cc0000'
  legend: 'ttLF'
  order: 3
  #scale: 0.960297

'root16_qcd/hist_dataDriven_QCD_Pt-15to20_MuEnriched.root':
  type: mc
  pretty-name: 'QCD_Pt-15to20_MuEnriched'
  cross-section: 3819570.0
  generated-events: 4141251.0
  fill-color: '#d0cfd4'
  group: GQCD
  order: 19
  #scale: 0.936838

'root16_qcd/hist_dataDriven_QCD_Pt-20to30_MuEnriched.root':
  type: mc
  pretty-name: 'QCD_Pt-20to30_MuEnriched'
  cross-section: 2960198.4
  generated-events: 31475157.0
  fill-color: '#d0cfd4'
  group: GQCD
  order: 20
  #scale: 0.936838

'root16_qcd/hist_dataDriven_QCD_Pt-50to80_MuEnriched.root':
  type: mc
  pretty-name: 'QCD_Pt-50to80_MuEnriched'
  cross-section: 437504.1
  generated-events: 19806915.0
  fill-color: '#d0cfd4'
  group: GQCD
  order: 21
  #scale: 0.936838

'root16_qcd/hist_dataDriven_QCD_Pt-80to120_MuEnriched.root':
  type: mc
  pretty-name: 'QCD_Pt-80to120_MuEnriched'
  cross-section: 106033.6648
  generated-events: 13669116.0
  fill-color: '#d0cfd4'
  group: GQCD
  order: 22
  #scale: 0.936838

'root16_qcd/hist_dataDriven_QCD_Pt-120to170_MuEnriched.root':
  type: mc
  pretty-name: 'QCD_Pt-120to170_MuEnriched'
  cross-section: 25190.51514
  generated-events: 11938140.0
  fill-color: '#d0cfd4'
  group: GQCD
  order: 23
  #scale: 0.936838

'root16_qcd/hist_dataDriven_QCD_Pt-170to300_MuEnriched.root':
  type: mc
  pretty-name: 'QCD_Pt-170to300_MuEnriched'
  cross-section: 8654.49315
  generated-events: 7947159.0
  fill-color: '#d0cfd4'
  group: GQCD
  order: 24
  #scale: 0.936838

'root16_qcd/hist_dataDriven_QCD_Pt-300to470_MuEnriched.root':
  type: mc
  pretty-name: 'QCD_Pt-300to470_MuEnriched'
  cross-section: 797.35269
  generated-events: 16452588.0
  fill-color: '#d0cfd4'
  group: GQCD
  order: 25
  #scale: 0.936838

'root16_qcd/hist_dataDriven_QCD_Pt-470to600_MuEnriched.root':
  type: mc
  pretty-name: 'QCD_Pt-470to600_MuEnriched'
  cross-section: 79.02553776
  generated-events: 5663755.0
  fill-color: '#d0cfd4'
  group: GQCD
  order: 26
  #scale: 0.936838

'root16_qcd/hist_dataDriven_QCD_Pt-600to800_MuEnriched.root':
  type: mc
  pretty-name: 'QCD_Pt-600to800_MuEnriched'
  cross-section: 25.09505908
  generated-events: 5971175.0
  fill-color: '#d0cfd4'
  group: GQCD
  order: 27
  #scale: 0.936838

'root16_qcd/hist_dataDriven_QCD_Pt-800to1000_MuEnriched.root':
  type: mc
  pretty-name: 'QCD_Pt-800to1000_MuEnriched'
  cross-section: 4.707368272
  generated-events: 5838541.0
  fill-color: '#d0cfd4'
  group: GQCD
  order: 28
  #scale: 0.936838

'root16_qcd/hist_dataDriven_QCD_Pt-1000toInf_MuEnriched.root':
  type: mc
  pretty-name: 'QCD_Pt-1000toInf_MuEnriched'
  cross-section: 1.62131692
  generated-events: 9609821.0
  fill-color: '#d0cfd4'
  group: GQCD
  order: 29
  #scale: 0.936838

'root16_qcd/hist_dataDriven_QCD_Pt-20to30_EMEnriched.root':
  type: mc
  pretty-name: 'QCD_Pt-20to30_EMEnriched'
  cross-section: 5352960.0
  generated-events: 9218954.0
  fill-color: '#d0cfd4'
  group: GQCD
  order: 30
  #scale: 0.936838

'root16_qcd/hist_dataDriven_QCD_Pt-30to50_EMEnriched.root':
  type: mc
  pretty-name: 'QCD_Pt-30to50_EMEnriched'
  cross-section: 9928000.0
  generated-events: 6768384.0
  fill-color: '#d0cfd4'
  group: GQCD
  order: 31
  #scale: 0.936838

'root16_qcd/hist_dataDriven_QCD_Pt-50to80_EMEnriched.root':
  type: mc
  pretty-name: 'QCD_Pt-50to80_EMEnriched'
  cross-section: 2890800.0
  generated-events: 23474171.0
  fill-color: '#d0cfd4'
  group: GQCD
  order: 32
  #scale: 0.936838

'root16_qcd/hist_dataDriven_QCD_Pt-80to120_EMEnriched.root':
  type: mc
  pretty-name: 'QCD_Pt-80to120_EMEnriched'
  cross-section: 350000.0
  generated-events: 41853504.0
  fill-color: '#d0cfd4'
  group: GQCD
  order: 33
  #scale: 0.936838

'root16_qcd/hist_dataDriven_QCD_Pt-120to170_EMEnriched.root':
  type: mc
  pretty-name: 'QCD_Pt-120to170_EMEnriched'
  cross-section: 62964.0
  generated-events: 35817281.0
  fill-color: '#d0cfd4'
  group: GQCD
  order: 34
  #scale: 0.936838

'root16_qcd/hist_dataDriven_QCD_Pt-170to300_EMEnriched.root':
  type: mc
  pretty-name: 'QCD_Pt-170to300_EMEnriched'
  cross-section: 18810.0
  generated-events: 11540163.0
  fill-color: '#d0cfd4'
  group: GQCD
  order: 35
  #scale: 0.936838

'root16_qcd/hist_dataDriven_QCD_Pt-300toInf_EMEnriched.root':
  type: mc
  pretty-name: 'QCD_Pt-300toInf_EMEnriched'
  cross-section: 1350.0
  generated-events: 7373633.0
  fill-color: '#d0cfd4'
  group: GQCD
  order: 36
  #scale: 0.936838

