'root17_test/hist_Nosys_DataSingleMu.root':
  type: data
  legend: 'Data'
  pretty-name: 'DataMu'
  marker-size: 0.6
  group: GData

'root17_test/hist_Nosys_DataSingleEG.root':
  type: data
  legend: 'Data'
  pretty-name: 'DataEG'
  marker-size: 0.6
  group: GData

'root17_test/hist_Nosys_ttZToQQ_aMCatNLOMadspinPythia.root':
  type: mc
  pretty-name: 'ttZToQQ_aMCatNLOMadspinPythia'
  cross-section: 0.5297
  generated-events: 356286.0
  fill-color: '#ff66ff'
  group: GttX
  order: 12

'root17_test/hist_Nosys_ttZToLLNuNu_aMCatNLOMadspinPythia.root':
  type: mc
  pretty-name: 'ttZToLLNuNu_aMCatNLOMadspinPythia'
  cross-section: 0.2529
  generated-events: 3570720.0
  fill-color: '#ff66ff'
  group: GttX
  order: 13

'root17_test/hist_Nosys_ttWToQQ_aMCatNLOMadspinPythia.root':
  type: mc
  pretty-name: 'ttWToQQ_aMCatNLOMadspinPythia'
  cross-section: 0.4062
  generated-events: 441560.0
  fill-color: '#ff66ff'
  group: GttX
  order: 10

'root17_test/hist_Nosys_ttWToLNu_aMCatNLOMadspinPythia.root':
  type: mc
  pretty-name: 'ttWToLNu_aMCatNLOMadspinPythia'
  cross-section: 0.2043
  generated-events: 2686141.0
  fill-color: '#ff66ff'
  group: GttX
  order: 11

'root17_test/hist_Nosys_ttHTobb_PowhegPythia.root':
  type: mc
  pretty-name: 'ttHTobb_PowhegPythia'
  cross-section: 0.2923
  generated-events: 7833734.0
  fill-color: '#ff66ff'
  group: GttX
  order: 8

'root17_test/hist_Nosys_ttHToNonbb_PowhegPythia.root':
  type: mc
  pretty-name: 'ttHToNonbb_PowhegPythia'
  cross-section: 0.2151
  generated-events: 7814711.0
  fill-color: '#ff66ff'
  group: GttX
  order: 9

'root17_test/hist_Nosys_ZZ_Pythia.root':
  type: mc
  pretty-name: 'ZZ_Pythia'
  cross-section: 16.523
  generated-events: 1949768.0
  fill-color: '#00cccc'
  group: GVV
  order: 21

'root17_test/hist_Nosys_ZJets_M50_aMCatNLOPythia.root':
  type: mc
  pretty-name: 'ZJets_M50_aMCatNLOPythia'
  cross-section: 6225.42
  generated-events: 123485957.0
  fill-color: '#000099'
  group: GZJets
  order: 22

'root17_test/hist_Nosys_ZJets_M10to50_MadgraphPythia.root':
  type: mc
  pretty-name: 'ZJets_M10to50_MadgraphPythia'
  cross-section: 18610.0
  generated-events: 39489654.0
  fill-color: '#000099'
  group: GZJets
  order: 23

'root17_test/hist_Nosys_WZ_Pythia.root':
  type: mc
  pretty-name: 'WZ_Pythia'
  cross-section: 47.13
  generated-events: 3928630.0
  fill-color: '#00cccc'
  group: GVV
  order: 20

'root17_test/hist_Nosys_WW_Pythia.root':
  type: mc
  pretty-name: 'WW_Pythia'
  cross-section: 118.7
  generated-events: 7791498.0
  fill-color: '#00cccc'
  group: GVV
  order: 19

'root17_test/hist_Nosys_WJetsToLNu_MadgraphPythia.root':
  type: mc
  pretty-name: 'WJetsToLNu_MadgraphPythia'
  cross-section: 61526.7
  generated-events: 77631180.0
  fill-color: '#ff9933'
  legend: 'WJets'
  order: 24

'root17_test/hist_Nosys_TTLL_PowhegPythiaBkg.root':
  type: mc
  pretty-name: 'TTLL_PowhegPythiaBkg'
  cross-section: 88.29
  generated-events: 68595608.0
  fill-color: '#ff6666'
  group: GttBkg
  order: 5

'root17_test/hist_Nosys_TTLJ_PowhegPythia_ttother.root':
  type: mc
  pretty-name: 'TTLJ_PowhegPythia_ttother'
  cross-section: 365.34
  generated-events: 109124472.0
  fill-color: '#ff6666'
  group: GttBkg
  order: 4

'root17_test/hist_Nosys_TTLJ_PowhegPythia_ttcc.root':
  type: mc
  pretty-name: 'TTLJ_PowhegPythia_ttcc'
  cross-section: 365.34
  generated-events: 109124472.0
  fill-color: '#990000'
  legend: 'ttcc'
  order: 2

'root17_test/hist_Nosys_TTLJ_PowhegPythia_ttbj.root':
  type: mc
  pretty-name: 'TTLJ_PowhegPythia_ttbj'
  cross-section: 365.34
  generated-events: 109124472.0
  fill-color: '#660000'
  legend: 'ttbj'
  order: 1

'root17_test/hist_Nosys_TTLJ_PowhegPythia_ttbb.root':
  type: mc
  pretty-name: 'TTLJ_PowhegPythia_ttbb'
  cross-section: 365.34
  generated-events: 109124472.0
  fill-color: '#330000'
  legend: 'ttbb'
  order: 0

'root17_test/hist_Nosys_TTLJ_PowhegPythia_ttLF.root':
  type: mc
  pretty-name: 'TTLJ_PowhegPythia_ttLF'
  cross-section: 365.34
  generated-events: 109124472.0
  fill-color: '#cc0000'
  legend: 'ttLF'
  order: 3

'root17_test/hist_Nosys_TTLJ_PowhegPythiaBkg.root':
  type: mc
  pretty-name: 'TTLJ_PowhegPythiaBkg'
  cross-section: 365.34
  generated-events: 109124472.0
  fill-color: '#ff6666'
  group: GttBkg
  order: 6

'root17_test/hist_Nosys_TTJJ_PowhegPythiaBkg.root':
  type: mc
  pretty-name: 'TTJJ_PowhegPythiaBkg'
  cross-section: 377.96
  generated-events: 129211204.0
  fill-color: '#ff6666'
  group: GttBkg
  order: 7

'root17_test/hist_Nosys_SingleTop_t_PowhegPythia.root':
  type: mc
  pretty-name: 'SingleTop_t_PowhegPythia'
  cross-section: 136.02
  generated-events: 5982064.0
  fill-color: '#990099'
  group: GSingleT
  order: 14

'root17_test/hist_Nosys_SingleTop_tW_PowhegPythia.root':
  type: mc
  pretty-name: 'SingleTop_tW_PowhegPythia'
  cross-section: 35.85
  generated-events: 7884388.0
  fill-color: '#990099'
  group: GSingleT
  order: 15

'root17_test/hist_Nosys_SingleTop_s_aMCatNLOPythia.root':
  type: mc
  pretty-name: 'SingleTop_s_aMCatNLOPythia'
  cross-section: 3.36
  generated-events: 6185062.0
  fill-color: '#990099'
  group: GSingleT
  order: 16

'root17_test/hist_Nosys_SingleTbar_t_PowhegPythia.root':
  type: mc
  pretty-name: 'SingleTbar_t_PowhegPythia'
  cross-section: 80.95
  generated-events: 3675910.0
  fill-color: '#990099'
  group: GSingleT
  order: 17

'root17_test/hist_Nosys_SingleTbar_tW_PowhegPythia.root':
  type: mc
  pretty-name: 'SingleTbar_tW_PowhegPythia'
  cross-section: 35.85
  generated-events: 7686032.0
  fill-color: '#990099'
  group: GSingleT
  order: 18

'root17_test/hist_Nosys_QCD_Pt-15to20_MuEnriched.root':
  type: mc
  pretty-name: 'QCD_Pt-15to20_MuEnriched'
  cross-section: 3819570.0
  generated-events: 5859904.0
  fill-color: '#d0cfd4'
  group: GQCD
  order: 29

'root17_test/hist_Nosys_QCD_Pt-20to30_MuEnriched.root':
  type: mc
  pretty-name: 'QCD_Pt-20to30_MuEnriched'
  cross-section: 2960198.4
  generated-events: 28213684.0
  fill-color: '#d0cfd4'
  group: GQCD
  order: 30

'root17_test/hist_Nosys_QCD_Pt-50to80_MuEnriched.root':
  type: mc
  pretty-name: 'QCD_Pt-50to80_MuEnriched'
  cross-section: 437504.1
  generated-events: 24068613.0
  fill-color: '#d0cfd4'
  group: GQCD
  order: 31

'root17_test/hist_Nosys_QCD_Pt-80to120_MuEnriched.root':
  type: mc
  pretty-name: 'QCD_Pt-80to120_MuEnriched'
  cross-section: 106033.6648
  generated-events: 23248995.0
  fill-color: '#d0cfd4'
  group: GQCD
  order: 32

'root17_test/hist_Nosys_QCD_Pt-120to170_MuEnriched.root':
  type: mc
  pretty-name: 'QCD_Pt-120to170_MuEnriched'
  cross-section: 25190.51514
  generated-events: 20774848.0
  fill-color: '#d0cfd4'
  group: GQCD
  order: 33

'root17_test/hist_Nosys_QCD_Pt-170to300_MuEnriched.root':
  type: mc
  pretty-name: 'QCD_Pt-170to300_MuEnriched'
  cross-section: 8654.49315
  generated-events: 46170668.0
  fill-color: '#d0cfd4'
  group: GQCD
  order: 34

'root17_test/hist_Nosys_QCD_Pt-300to470_MuEnriched.root':
  type: mc
  pretty-name: 'QCD_Pt-300to470_MuEnriched'
  cross-section: 797.35269
  generated-events: 17744779.0
  fill-color: '#d0cfd4'
  group: GQCD
  order: 35

'root17_test/hist_Nosys_QCD_Pt-470to600_MuEnriched.root':
  type: mc
  pretty-name: 'QCD_Pt-470to600_MuEnriched'
  cross-section: 79.02553776
  generated-events: 24243589.0
  fill-color: '#d0cfd4'
  group: GQCD
  order: 36

'root17_test/hist_Nosys_QCD_Pt-600to800_MuEnriched.root':
  type: mc
  pretty-name: 'QCD_Pt-600to800_MuEnriched'
  cross-section: 25.09505908
  generated-events: 17263676.0
  fill-color: '#d0cfd4'
  group: GQCD
  order: 37

'root17_test/hist_Nosys_QCD_Pt-800to1000_MuEnriched.root':
  type: mc
  pretty-name: 'QCD_Pt-800to1000_MuEnriched'
  cross-section: 4.707368272
  generated-events: 17114527.0
  fill-color: '#d0cfd4'
  group: GQCD
  order: 38

'root17_test/hist_Nosys_QCD_Pt-1000toInf_MuEnriched.root':
  type: mc
  pretty-name: 'QCD_Pt-1000toInf_MuEnriched'
  cross-section: 1.621311692
  generated-events: 11596693.0
  fill-color: '#d0cfd4'
  group: GQCD
  order: 39

'root17_test/hist_Nosys_QCD_Pt-15to20_EMEnriched.root':
  type: mc
  pretty-name: 'QCD_Pt-15to20_EMEnriched'
  cross-section: 2302200.0
  generated-events: 11215220.0
  fill-color: '#d0cfd4'
  group: GQCD
  order: 40

'root17_test/hist_Nosys_QCD_Pt-20to30_EMEnriched.root':
  type: mc
  pretty-name: 'QCD_Pt-20to30_EMEnriched'
  cross-section: 5352960.0
  generated-events: 11212810.0
  fill-color: '#d0cfd4'
  group: GQCD
  order: 41

'root17_test/hist_Nosys_QCD_Pt-30to50_EMEnriched.root':
  type: mc
  pretty-name: 'QCD_Pt-30to50_EMEnriched'
  cross-section: 9928000.0
  generated-events: 14766010.0
  fill-color: '#d0cfd4'
  group: GQCD
  order: 42

'root17_test/hist_Nosys_QCD_Pt-50to80_EMEnriched.root':
  type: mc
  pretty-name: 'QCD_Pt-50to80_EMEnriched'
  cross-section: 2890800.0
  generated-events: 10477146.0
  fill-color: '#d0cfd4'
  group: GQCD
  order: 43

'root17_test/hist_Nosys_QCD_Pt-80to120_EMEnriched.root':
  type: mc
  pretty-name: 'QCD_Pt-80to120_EMEnriched'
  cross-section: 350000.0
  generated-events: 9104852.0
  fill-color: '#d0cfd4'
  group: GQCD
  order: 44

'root17_test/hist_Nosys_QCD_Pt-120to170_EMEnriched.root':
  type: mc
  pretty-name: 'QCD_Pt-120to170_EMEnriched'
  cross-section: 62964.0
  generated-events: 8515107.0
  fill-color: '#d0cfd4'
  group: GQCD
  order: 45

'root17_test/hist_Nosys_QCD_Pt-300toInf_EMEnriched.root':
  type: mc
  pretty-name: 'QCD_Pt-300toInf_EMEnriched'
  cross-section: 1350.0
  generated-events: 2874295.0
  fill-color: '#d0cfd4'
  group: GQCD
  order: 46

