hist_DataSingleMu.root:
  type: data
  legend: 'Data'
  pretty-name: 'DataMu'
  marker-size: 0.6
  group: GData

hist_DataSingleEG.root:
  type: data
  legend: 'Data'
  pretty-name: 'DataEG'
  marker-size: 0.6
  group: GData

hist_TTLJ_PowhegPythia_ttbb.root:
  type: mc
  pretty-name: 'TTLJ_PowhegPythia_ttbb'
  cross-section: 365.34
  generated-events: 106736180.0
  fill-color: '#330000'
  legend: 'ttbb'
  order: 1

hist_TTLJ_PowhegPythia_ttbj.root:
  type: mc
  pretty-name: 'TTLJ_PowhegPythia_ttbj'
  cross-section: 365.34
  generated-events: 106736180.0
  fill-color: '#660000'
  legend: 'ttbj'
  order: 2

hist_TTLJ_PowhegPythia_ttcc.root:
  type: mc
  pretty-name: 'TTLJ_PowhegPythia_ttcc'
  cross-section: 365.34
  generated-events: 106736180.0
  fill-color: '#990000'
  legend: 'ttcc'
  order: 3

hist_TTLJ_PowhegPythia_ttLF.root:
  type: mc
  pretty-name: 'TTLJ_PowhegPythia_ttLF'
  cross-section: 365.34
  generated-events: 106736180.0
  fill-color: '#cc0000'
  legend: 'ttLF'
  order: 4

hist_TTLJ_PowhegPythia_ttother.root:
  type: mc
  pretty-name: 'TTLJ_PowhegPythia_ttother'
  cross-section: 365.34
  generated-events: 106736180.0
  fill-color: '#ff6666'
  group: GttBkg
  order: 5

hist_TTLJ_PowhegPythiaBkg.root:
  type: mc
  pretty-name: 'TTLJ_PowhegPythiaBkg'
  cross-section: 365.34
  generated-events: 106736180.0
  fill-color: '#ff6666'
  group: GttBkg
  order: 6

hist_TTLL_PowhegPythiaBkg.root:
  type: mc
  pretty-name: 'TTLL_PowhegPythiaBkg'
  cross-section: 88.29
  generated-events: 67312164.0
  fill-color: '#ff6666'
  group: GttBkg
  order: 7

hist_TTJJ_PowhegPythiaBkg.root:
  type: mc
  pretty-name: 'TTJJ_PowhegPythiaBkg'
  cross-section: 377.96
  generated-events: 67963984.0
  fill-color: '#ff6666'
  group: GttBkg
  order: 8

hist_SingleTop_s_aMCatNLOPythia.root:
  type: mc
  pretty-name: 'SingleTop_s_aMCatNLOPythia'
  cross-section: 3.36
  generated-events: 6137801.0
  fill-color: '#990099'
  group: GSingleT
  order: 9

hist_SingleTop_t_PowhegPythia.root:
  type: mc
  pretty-name: 'SingleTop_t_PowhegPythia'
  cross-section: 136.02
  generated-events: 31848000.0
  fill-color: '#990099'
  group: GSingleT
  order: 10

hist_SingleTop_tW_PowhegPythia.root:
  type: mc
  pretty-name: 'SingleTop_tW_PowhegPythia'
  cross-section: 35.85
  generated-events: 4945734.0
  fill-color: '#990099'
  group: GSingleT
  order: 11

hist_SingleTbar_t_PowhegPythia.root:
  type: mc
  pretty-name: 'SingleTbar_t_PowhegPythia'
  cross-section: 80.95
  generated-events: 17780700.0
  fill-color: '#990099'
  group: GSingleT
  order: 12

hist_SingleTbar_tW_PowhegPythia.root:
  type: mc
  pretty-name: 'SingleTbar_tW_PowhegPythia'
  cross-section: 35.85
  generated-events: 4942374.0
  fill-color: '#990099'
  group: GSingleT
  order: 13

hist_ttZToQQ_aMCatNLOMadspinPythia.root:
  type: mc
  pretty-name: 'ttZToQQ_aMCatNLOMadspinPythia'
  cross-section: 0.5297
  generated-events: 351164.0
  fill-color: '#ff66ff'
  group: GttX
  order: 11

hist_ttZToLLNuNu_aMCatNLOMadspinPythia.root:
  type: mc
  pretty-name: 'ttZToLLNuNu_aMCatNLOMadspinPythia'
  cross-section: 0.2529
  generated-events: 6420825.0
  fill-color: '#ff66ff'
  group: GttX
  order: 12

hist_ttWToQQ_aMCatNLOMadspinPythia.root:
  type: mc
  pretty-name: 'ttWToQQ_aMCatNLOMadspinPythia'
  cross-section: 0.4062
  generated-events: 430310.0
  fill-color: '#ff66ff'
  group: GttX
  order: 13

hist_ttWToLNu_aMCatNLOMadspinPythia.root:
  type: mc
  pretty-name: 'ttWToLNu_aMCatNLOMadspinPythia'
  cross-section: 0.2043
  generated-events: 2716249.0
  fill-color: '#ff66ff'
  group: GttX
  order: 14

hist_ttHTobb_PowhegPythia.root:
  type: mc
  pretty-name: 'ttHTobb_PowhegPythia'
  cross-section: 0.2934
  generated-events: 9764780.0
  fill-color: '#ff66ff'
  group: GttX
  order: 14

hist_ttHToNonbb_PowhegPythia.root:
  type: mc
  pretty-name: 'ttHToNonbb_PowhegPythia'
  cross-section: 0.2151
  generated-events: 9757039.0
  fill-color: '#ff66ff'
  group: GttX
  order: 15

hist_WW_Pythia.root:
  type: mc
  pretty-name: 'WW_Pythia'
  cross-section: 118.7
  generated-events: 7837160.0
  fill-color: '#00cccc'
  group: GVV
  order: 17

hist_WZ_Pythia.root:
  type: mc
  pretty-name: 'WZ_Pythia'
  cross-section: 47.13
  generated-events: 3997571.0
  fill-color: '#00cccc'
  group: GVV
  order: 18

hist_ZZ_Pythia.root:
  type: mc
  pretty-name: 'ZZ_Pythia'
  cross-section: 16.523
  generated-events: 1988098.0
  fill-color: '#00cccc'
  group: GVV
  order: 19

hist_ZJets_M10to50_MadgraphPythia.root:
  type: mc
  pretty-name: 'ZJets_M10to50_MadgraphPythia'
  cross-section: 18610.0
  generated-events: 78843820.0
  fill-color: '#000099'
  group: GZJets
  order: 20

hist_ZJets_M50_aMCatNLOPythia.root:
  type: mc
  pretty-name: 'ZJets_M50_aMCatNLOPythia'
  cross-section: 6077.22
  generated-events: 80478895.0
  fill-color: '#000099'
  group: GZJets
  order: 21

hist_W1JetsToLNu_MadgraphPythia.root:
  type: mc
  pretty-name: 'W1JetsToLNu_MadgraphPythia'
  cross-section: 9625.0
  generated-events: 45283121.0
  fill-color: '#ff9933'
  group: GWJets
  order: 22

hist_W2JetsToLNu_MadgraphPythia.root:
  type: mc
  pretty-name: 'W2JetsToLNu_MadgraphPythia'
  cross-section: 2793.0
  generated-events: 60438768.0
  fill-color: '#ff9933'
  group: GWJets
  order: 23

hist_W3JetsToLNu_MadgraphPythia.root:
  type: mc
  pretty-name: 'W3JetsToLNu_MadgraphPythia'
  cross-section: 992.5
  generated-events: 59300029.0
  fill-color: '#ff9933'
  group: GWJets
  order: 24

hist_W4JetsToLNu_MadgraphPythia.root:
  type: mc
  pretty-name: 'W4JetsToLNu_MadgraphPythia'
  cross-section: 544.3
  generated-events: 11189932.0
  fill-color: '#ff9933'
  group: GWJets
  order: 25

hist_QCD_Pt-15to20_MuEnriched.root:
  type: mc
  pretty-name: 'QCD_Pt-15to20_MuEnriched'
  cross-section: 3819570.0
  generated-events: 4141251.0
  fill-color: '#d0cfd4'
  group: GQCD
  order: 26

hist_QCD_Pt-20to30_MuEnriched.root:
  type: mc
  pretty-name: 'QCD_Pt-20to30_MuEnriched'
  cross-section: 2960198.4
  generated-events: 31878740.0
  fill-color: '#d0cfd4'
  group: GQCD
  order: 27

#hist_QCD_Pt-30to50_MuEnriched.root:
#  type: mc
#  pretty-name: 'QCD_Pt-30to50_MuEnriched'
#  cross-section: 1652471.46
#  generated-events: 29809492.0
#  fill-color: '#d0cfd4'
#  group: GQCD
#  order: 28

hist_QCD_Pt-50to80_MuEnriched.root:
  type: mc
  pretty-name: 'QCD_Pt-50to80_MuEnriched'
  cross-section: 437504.1
  generated-events: 19662175.0
  fill-color: '#d0cfd4'
  group: GQCD
  order: 29

hist_QCD_Pt-80to120_MuEnriched.root:
  type: mc
  pretty-name: 'QCD_Pt-80to120_MuEnriched'
  cross-section: 106033.6648
  generated-events: 23560662.0
  fill-color: '#d0cfd4'
  group: GQCD
  order: 30

hist_QCD_Pt-120to170_MuEnriched.root:
  type: mc
  pretty-name: 'QCD_Pt-120to170_MuEnriched'
  cross-section: 25190.51514
  generated-events: 7897731.0
  fill-color: '#d0cfd4'
  group: GQCD
  order: 31

hist_QCD_Pt-170to300_MuEnriched.root:
  type: mc
  pretty-name: 'QCD_Pt-170to300_MuEnriched'
  cross-section: 8654.49315
  generated-events: 17350231.0
  fill-color: '#d0cfd4'
  group: GQCD
  order: 32

hist_QCD_Pt-300to470_MuEnriched.root:
  type: mc
  pretty-name: 'QCD_Pt-300to470_MuEnriched'
  cross-section: 797.35269
  generated-events: 49005976.0
  fill-color: '#d0cfd4'
  group: GQCD
  order: 33

hist_QCD_Pt-470to600_MuEnriched.root:
  type: mc
  pretty-name: 'QCD_Pt-470to600_MuEnriched'
  cross-section: 79.02553776
  generated-events: 19489276.0
  fill-color: '#d0cfd4'
  group: GQCD
  order: 34

hist_QCD_Pt-600to800_MuEnriched.root:
  type: mc
  pretty-name: 'QCD_Pt-600to800_MuEnriched'
  cross-section: 25.09505908
  generated-events: 9981311.0
  fill-color: '#d0cfd4'
  group: GQCD
  order: 35

hist_QCD_Pt-800to1000_MuEnriched.root:
  type: mc
  pretty-name: 'QCD_Pt-800to1000_MuEnriched'
  cross-section: 4.707368272
  generated-events: 19940747.0
  fill-color: '#d0cfd4'
  group: GQCD
  order: 36

hist_QCD_Pt-1000toInf_MuEnriched.root:
  type: mc
  pretty-name: 'QCD_Pt-1000toInf_MuEnriched'
  cross-section: 1.62131692
  generated-events: 13577827.0
  fill-color: '#d0cfd4'
  group: GQCD
  order: 37

hist_QCD_Pt-20to30_EMEnriched.root:
  type: mc
  pretty-name: 'QCD_Pt-20to30_EMEnriched'
  cross-section: 5352960.0
  generated-events: 9241500.0
  fill-color: '#d0cfd4'
  group: GQCD
  order: 38

hist_QCD_Pt-30to50_EMEnriched.root:
  type: mc
  pretty-name: 'QCD_Pt-30to50_EMEnriched'
  cross-section: 9928000.0
  generated-events: 11508842.0
  fill-color: '#d0cfd4'
  group: GQCD
  order: 39

hist_QCD_Pt-50to80_EMEnriched.root:
  type: mc
  pretty-name: 'QCD_Pt-50to80_EMEnriched'
  cross-section: 2890800.0
  generated-events: 45789059.0
  fill-color: '#d0cfd4'
  group: GQCD
  order: 40

hist_QCD_Pt-80to120_EMEnriched.root:
  type: mc
  pretty-name: 'QCD_Pt-80to120_EMEnriched'
  cross-section: 350000.0
  generated-events: 77800204.0
  fill-color: '#d0cfd4'
  group: GQCD
  order: 41

hist_QCD_Pt-120to170_EMEnriched.root:
  type: mc
  pretty-name: 'QCD_Pt-120to170_EMEnriched'
  cross-section: 62964.0
  generated-events: 78578415.0
  fill-color: '#d0cfd4'
  group: GQCD
  order: 42

hist_QCD_Pt-170to300_EMEnriched.root:
  type: mc
  pretty-name: 'QCD_Pt-170to300_EMEnriched'
  cross-section: 18810.0
  generated-events: 11540163.0
  fill-color: '#d0cfd4'
  group: GQCD
  order: 43

hist_QCD_Pt-300toInf_EMEnriched.root:
  type: mc
  pretty-name: 'QCD_Pt-300toInf_EMEnriched'
  cross-section: 1350.0
  generated-events: 7380341.0
  fill-color: '#d0cfd4'
  group: GQCD
  order: 44

